### ISSUE TITLE
Improve w3gw binary error message

### ISSUE THREAD

**Issue by guidiaz** [witnet/web3-jsonrpc-gateway#65]
When specifying a network that's not currently supported.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/web3-jsonrpc-gateway/65?planning-poker) with Zenhub @aesedepece @gabaldon @guidiaz @aeweda
